# Generated by Django 6.0.6 on 2026-07-06 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('assistant', models.CharField(blank=True, default='', max_length=255)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('memories', models.JSONField(blank=True, default=list)),
                ('mcp_servers', models.JSONField(blank=True, default=list)),
                ('suggestion_enabled', models.BooleanField(default=False)),
                ('title_generation', models.BooleanField(default=True)),
                ('max_history', models.PositiveIntegerField(blank=True, null=True)),
                ('file_upload', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant Settings',
                'verbose_name_plural': 'Assistant Settings',
                'db_table': 'django_ai_sdk_runtime_assistants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_ai_sdk_documents',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_ai_sdk_memories',
            },
        ),
        migrations.CreateModel(
            name='EntryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='memories/documents/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_extension', models.CharField(blank=True, default='', max_length=20)),
                ('extracted', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='django_ai_sdk.entry')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='django_ai_sdk.memory')),
            ],
            options={
                'db_table': 'django_ai_sdk_entry_documents',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_ai_sdk.memory'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_files', to='django_ai_sdk.memory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_ai_sdk_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_ai_sdk.thread')),
            ],
            options={
                'db_table': 'django_ai_sdk_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(default='data_table', max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='django_ai_sdk.thread')),
            ],
            options={
                'db_table': 'django_ai_sdk_artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_links', to='django_ai_sdk.memory')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_links', to='django_ai_sdk.thread')),
            ],
            options={
                'db_table': 'django_ai_sdk_thread_memories',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('workflow_definition', models.JSONField(blank=True, null=True)),
                ('input_messages', models.JSONField(default=list)),
                ('outputs', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'db_table': 'django_ai_sdk_workflow_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('step_name', models.CharField(blank=True, default='', max_length=255)),
                ('output_key', models.CharField(max_length=255)),
                ('output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='django_ai_sdk.workflowrun')),
            ],
            options={
                'verbose_name': 'Workflow Run Step',
                'verbose_name_plural': 'Workflow Run Steps',
                'db_table': 'django_ai_sdk_workflow_run_steps',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.JSONField(default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'django_ai_sdk_workflows',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='django_ai_sdk.workflowsettings'),
        ),
        migrations.CreateModel(
            name='AssistantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_group_links', to='auth.group')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_groups', to='django_ai_sdk.assistantsettings')),
            ],
            options={
                'db_table': 'django_ai_sdk_runtime_assistant_groups',
                'unique_together': {('assistant', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AssistantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_users', to='django_ai_sdk.assistantsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_ai_sdk_runtime_assistant_users',
                'unique_together': {('assistant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='auth.group')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_groups', to='django_ai_sdk.memory')),
            ],
            options={
                'db_table': 'django_ai_sdk_memory_groups',
                'unique_together': {('memory', 'group')},
            },
        ),
        migrations.CreateModel(
            name='MemoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_users', to='django_ai_sdk.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_ai_sdk_memory_users',
                'unique_together': {('memory', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(choices=[(1, 'good'), (-1, 'bad')])),
                ('feedback', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='django_ai_sdk.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_ai_sdk_message_feedbacks',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='django_ai_s_thread__746f36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadmemory',
            unique_together={('thread', 'memory')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowrunstep',
            unique_together={('run', 'sequence')},
        ),
    ]
