# Generated by Django 5.2.15 on 2026-06-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrydocument",
            name="memory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="django_ai_sdk.memory",
            ),
        ),
    ]
