# Generated by Django 6.0.8 on 2026-09-09 11:43

from __future__ import annotations

from django.db import migrations, models

import django_ai_sdk.files.common


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrydocument",
            name="file",
            field=models.FileField(
                storage=django_ai_sdk.files.common.get_entry_document_storage,
                upload_to="memories/documents/",
            ),
        ),
    ]
