# Generated by Django 5.2.13 on 2026-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0002_memory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rating_comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
