# Generated by Django 6.0.6 on 2026-07-22 21:02

from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0002_assistantsettings_supports_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="chat/images/")),
                ("media_type", models.CharField(max_length=100)),
                (
                    "file_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="django_ai_sdk.message",
                    ),
                ),
            ],
            options={
                "db_table": "django_ai_sdk_message_images",
                "ordering": ["created_at"],
            },
        ),
    ]
