# Generated by Django 6.0.8 on 2026-09-09 14:00

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0002_add_custom_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
