# Generated by Django 5.2.15 on 2026-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0002_entrydocument_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsettings",
            name="allowed_groups",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="memories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assistantsettings",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
