# Generated by Django 6.0.2 on 2026-05-26 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0002_memory_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
