# Generated by Django 6.0.8 on 2026-09-28 13:33

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0003_move_workflows_to_workflows_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrydocument",
            name="processing_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
