# Generated by Django 6.0.8 on 2026-09-28 14:23

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk", "0004_entrydocument_processing_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsettings",
            name="required_tools",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agentsettings",
            name="vision",
            field=models.BooleanField(default=False),
        ),
    ]
