# Prompt template used for thread title generation.
TITLE_GENERATION_PROMPT: str = (
    "### Task:\n"
    "Generate a concise, 3-5 word title summarizing the chat history.\n\n"
    "### Guidelines:\n"
    "- The title should clearly represent the main theme or subject of the conversation.\n"
    "- Start the title with a single emoji that enhances understanding of the topic.\n"
    "- Write the title in the same language as the user's messages; "
    "default to English if multilingual or unclear.\n"
    "- Match the tone and register of the user (formal, casual, technical, etc.).\n"
    "- Prioritize accuracy over creativity; keep it clear and simple.\n\n"
    "### Output rules (strict):\n"
    "- Return ONLY the title. No preamble, no explanation, no commentary.\n"
    "- No markdown, no quotes, no backticks, no code fences.\n"
    "- A single line of plain text.\n\n"
    "### Examples:\n"
    "- 📉 Stock Market Trends\n"
    "- 🍪 Perfect Chocolate Chip Recipe\n"
    "- 🎮 Video Game Development Insights\n\n"
    "### Chat History:\n{chat_history}"
)
