# Generated by Django 6.0.8 on 2026-09-01 08:44

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_ai_sdk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_name", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=255)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="django_ai_sdk.message",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="django_ai_sdk_tracing.trace",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="django_ai_sdk.thread",
                    ),
                ),
            ],
            options={
                "db_table": "django_ai_sdk_traces",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["operation_name", "started_at"],
                        name="django_ai_s_operati_5168ae_idx",
                    ),
                    models.Index(
                        fields=["thread", "started_at"], name="django_ai_s_thread__6427ec_idx"
                    ),
                ],
            },
        ),
    ]
