# Generated by Django 6.0.8 on 2026-09-03 12:07

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk_tracing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="agent_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
