# Generated by Django 6.0.8 on 2026-09-04 07:45

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ai_sdk_tracing", "0002_trace_agent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="agent_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
